//constant constants
const constants={
    JumpQualifier:1,
    SK8_OFFSET_FROM_LEFT:40,
    SK8_WIDTH:160,
    SK8_FROM_CENTER_TO_WHEEL:50,
    SK8_HEIGHT:25,
    SK8_THICK:5,
    WHEEL_RADIUS:10,
    BOLTS_RADIUS:3,
    SHADE_RADIUS:6,
    CONCRETE_HEIGHT:20,
    DRAIN_WIDTH:90,
    DRAIN_HEIGHT:18,
    QUATERPIPE_SIZE:100,
    QUATERPIPE_THICK:30,
    STARTING_SPEED:50,
    SPEEDTHINGS_WIDTH:30,
    SPEEDTHINGS_HEIGHT:4,
    SPEEDTHINGIES:[10,150,290],
    DRAINS:[1000,2000],
    QUATERPIPE:5000,
    BACKQUATERPIPE:-1000
};


const DRAIN_COLOR='#111';
const SPEEDTHINGS_COLOR='#666';
const WHEEL_COLOR='#FFF';
const SHADE_COLOR='#AAAE';
const DECK_COLOR='#642';
const GRIPTAPE_COLOR='#000';
const BOLTS_COLOR='#CCC';
const BACKGROUND_COLOR='#333';
const CONCRETE_COLOR='#999';
const QUATERPIPE_COLOR='#777';
const OVERLAY_COLOR='#FFF5';

const TRICK_SEQUENCE_COLOR='#00FD';



const SKATEBOARDING_COLOR='#ff9234';
const SKATEBOARDING_OUTLINE_COLOR='#ffcd3c';
const START_SCREEN_INSTRUCTIONS_COLOR='#f6cd61';
const GO_BACK_OVERLAY_COLOR='#F009';
const TUTORIAL_COLOR='#0A0';
const TUTORIAL_SECONDARY_COLOR='#00F9';

const TITLE_FONT='"Comic Sans MS", cursive, sans-serif';
const SECOND_FONT='Impact, Charcoal, sans-serif';
const THIRD_FONT='"Lucida Console", Monaco, monospace';


const TIME_AFTER_HIT=1500;